version: '3.8'

services:
  netaudit:
    build:
      context: .
      dockerfile: Dockerfile_production
    container_name: netaudit-webapp
    ports:
      - "5000:5000"
    volumes:
      - ./reports:/app/reports
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    network_mode: host  # Required for network scanning
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true  # Required for packet capture
    restart: unless-stopped
    
  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: netaudit-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Optional SSL certificates
    depends_on:
      - netaudit
    restart: unless-stopped
    profiles:
      - production 